import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { motion } from "framer-motion";
import Header from "../components/Header";
import Hero from "../components/Hero";
import About from "../components/About";
import Experience from "../components/Experience";
import Skills from "../components/Skills";
import Projects from "../components/Projects";
import ContactMe from "../components/ContactMe";

export default function Home() {
	return (
		<div
			className="h-screen snap-y snap-mandatory overflow-y-scroll overflow-x-hidden scroll-smooth z-0 scrollbar scrollbar-track-neutral-400/20
		scrollbar-thumb-neutral-400/80"
		>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header />
			<main>
				<section id="hero" className="snap-start">
					<Hero />
				</section>

				<section id="about" className="snap-center">
					<About />
				</section>

				<section id="experience" className="snap-center">
					<Experience />
				</section>

				<section id="skills" className="snap-start">
					<Skills />
				</section>

				<section id="projects" className="snap-start">
					<Projects />
				</section>

				<section id="contact" className="snap-start">
					<ContactMe />
				</section>
			</main>
		</div>
	);
}
